import Head from "next/head";
import { useState, useEffect } from "react";
import Agora, { RtcTokenBuilder, RtmTokenBuilder } from "agora-access-token";
import { useRouter } from "next/router";
import { db } from "../utils/firebase";
import useFirestore from "../hooks/useFirestore";
import Constants from "../utils/Constants";
import { Flip, toast, ToastContainer } from "react-toastify";

import { injectStyle } from "react-toastify/dist/inject-style";

export default function Home({ user }) {
  console.log("user", user);
  const [channel, setChannel] = useState("");

  const { updateChannel } = useFirestore(db);

  const router = useRouter();

  useEffect(() => {
    if (typeof window !== "undefined") {
      injectStyle();
    }
    if (router.query.st == 1) {
      toast.dark("please enter a valid meeting code", {
        position: "bottom-left",
        autoClose: 500,
        hideProgressBar: true,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
        transition: Flip,
      });
    }
    if (router.query.st == 2) {
      toast.dark("already logged in", {
        position: "bottom-left",
        autoClose: 500,
        hideProgressBar: true,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
        transition: Flip,
      });
    }
  }, []);
  const generateMeetingCode = () => {
    let meetingCode = "";
    const alphabets = "abcdefghijklmnopqrstuvwxyz";
    // generate random alphabet
    for (let i = 1; i <= 3; i++) {
      meetingCode += alphabets[Math.floor(Math.random() * alphabets.length)];
    }
    meetingCode += "-";
    for (let i = 1; i <= 4; i++) {
      meetingCode += alphabets[Math.floor(Math.random() * alphabets.length)];
    }
    meetingCode += "-";
    for (let i = 1; i <= 3; i++) {
      meetingCode += alphabets[Math.floor(Math.random() * alphabets.length)];
    }
    return meetingCode;
  };

  const createMeeting = () => {
    const generatedChannel = generateMeetingCode();
    const appId = "eaba463a5db445fda89361ca451604e3";
    const appCertificate = "697bd8f3d2a547c9b9a05d2c8e981d72";
    const expiresAt = Math.floor(Date.now() / 1000) + 2 * 60 * 60;

    const token = RtcTokenBuilder.buildTokenWithUid(
      appId,
      appCertificate,
      generatedChannel,
      user.uid,
      Agora.RtcRole.PUBLISHER,
      expiresAt
    );
    let rtmToken = RtmTokenBuilder.buildToken(
      appId,
      appCertificate,
      user.uid,
      Agora.RtcRole.PUBLISHER,
      expiresAt
    );

    updateChannel(generatedChannel, {
      channel: generatedChannel,
      token: token,
      rtmToken: rtmToken,
      createdBy: user.uid,
      timestamp: Date.now(),
    });
    router.push(`/${channel ? channel : generatedChannel}`);
  };

  return (
    <div className="bg-gray-800">
      <Head>
        <title>React video call</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" h-screen">
        <div class=" mb-4 relative items-center justify-center flex">
          <div
            className="m-10 flex h-12 collapse-on-tab-width"
            style={{ width: "min(500px, 90vw)" }}
          >
            <button
              class="shadow-sm w-1/2 mb-0 text-white bg-green-800 border-0 py-2 px-6 focus:outline-none transition-all duration-500 hover:bg-green-900 rounded text-lg"
              onClick={createMeeting}
            >
              New meeting
            </button>

            <input
              type="channel"
              id="channel"
              name="channel"
              autoCorrect="off"
              class="shadow-md  ml-4 flex-row-reverse w-full bg-gray-600 rounded border border-gray-500 text-white focus:border-gray-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
              placeholder="Enter a code"
              onChange={(event) => {
                setChannel(event.target.value.toLowerCase());
              }}
              value={channel}
              onKeyDown={(event) => {
                if (event.key === "Enter") {
                  router.push(`/${channel}`);
                }
              }}
            />
          </div>
        </div>
        <ToastContainer />
      </div>
    </div>
  );
}
